<?xml version="1.0"?>
<robot name="me332_mobile_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="controllers_yaml" default=""/>
  <xacro:property name="controllers_yaml_path" value="$(arg controllers_yaml)"/>

  <xacro:property name="PI" value="3.14159265359"/>
  <xacro:property name="PI_2" value="1.57079632679"/>
  
  <xacro:macro name="inertial_simple" params="mass ixx:=0.01 iyy:=0.01 izz:=0.01">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
    </inertial>
  </xacro:macro>

  <xacro:property name="color_body"   value="0.15 0.16 0.18 1.0"/>
  <xacro:property name="color_panel"  value="0.80 0.80 0.82 1.0"/>
  <xacro:property name="color_wheel"  value="0.05 0.05 0.05 1.0"/>
  <xacro:property name="color_joint"  value="0.95 0.55 0.10 1.0"/> 

  <xacro:property name="chassis_L" value="0.29"/>
  <xacro:property name="chassis_W" value="0.26"/>
  <xacro:property name="chassis_H" value="0.05"/>
  <xacro:property name="wheel_r" value="0.05"/>
  <xacro:property name="wheel_w" value="0.03"/>
  <xacro:property name="wheel_sep" value="0.24"/>
  <xacro:property name="wheel_x_offset" value="0.09"/> 

  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>



  <link name="base_link">
    <xacro:inertial_simple mass="60.0" ixx="0.25" iyy="0.25" izz="0.5"/>
    <visual>
      <origin xyz="0 0 ${0.5*chassis_H + 0.010}" rpy="0 0 0"/>
      <geometry><box size="${chassis_L} ${chassis_W} ${chassis_H}"/></geometry>
      <material name="base_body"><color rgba="${color_body}"/></material>
    </visual>
    <visual>
      <origin xyz="0 0 ${0.5*chassis_H + 0.040}" rpy="0 0 0"/>
      <geometry><box size="${chassis_L*0.78} ${chassis_W*0.78} 0.012"/></geometry>
      <material name="base_panel"><color rgba="${color_panel}"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 ${0.5*chassis_H + 0.010}" rpy="0 0 0"/>
      <geometry><box size="${chassis_L} ${chassis_W} ${chassis_H}"/></geometry>
    </collision>
  </link>



  <xacro:macro name="wheel_unit" params="prefix location_prefix x_pos reflect mu2_val:=200.0">
    <link name="${prefix}_wheel_link">
      <xacro:inertial_simple mass="1.0" ixx="0.0015" iyy="0.0015" izz="0.0015"/>
      <visual>
        <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
        <geometry><cylinder radius="${wheel_r}" length="${wheel_w}"/></geometry>
        <material name="wheel_mat_${prefix}"><color rgba="${color_wheel}"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
        <geometry><cylinder radius="${wheel_r}" length="${wheel_w}"/></geometry>
      </collision>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_pos} ${reflect * wheel_sep/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="500.0" velocity="5.0"/> 
      <dynamics damping="0.3" friction="0.3"/>
    </joint>

    <gazebo reference="${prefix}_wheel_link">
      <mu1>100.0</mu1> 
      <mu2>${mu2_val}</mu2> 
      <kp>10000000.0</kp>
      <kd>1.0</kd>
      <fdir1>1 0 0</fdir1>
      <minDepth>0.001</minDepth>
      <maxVel>0.1</maxVel>
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>

  <xacro:wheel_unit prefix="front_left"  location_prefix="front" x_pos="${wheel_x_offset}"  reflect="1"  mu2_val="0.1"/>
  <xacro:wheel_unit prefix="front_right" location_prefix="front" x_pos="${wheel_x_offset}"  reflect="-1" mu2_val="0.1"/>
  <xacro:wheel_unit prefix="rear_left"   location_prefix="rear"  x_pos="-${wheel_x_offset}" reflect="1"  mu2_val="200.0"/>
  <xacro:wheel_unit prefix="rear_right"  location_prefix="rear"  x_pos="-${wheel_x_offset}" reflect="-1" mu2_val="200.0"/>

  <link name="arm_base_link">
    <xacro:inertial_simple mass="1.0" ixx="0.002" iyy="0.002" izz="0.004"/>
    <visual>
      <origin xyz="0 0 0.0075" rpy="0 0 0"/>
      <geometry><cylinder radius="0.08" length="0.015"/></geometry>
      <material name="arm_base_mat"><color rgba="0.8 0.8 0.8 1"/></material>
    </visual>
  </link>
  
  <joint name="arm_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link"/>
    <origin xyz="0 0 ${chassis_H + 0.011}" rpy="0 0 0"/>
  </joint>
  
  <joint name="joint1" type="revolute">
    <parent link="arm_base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${PI}" upper="${PI}" effort="30.0" velocity="1.5"/>
    <dynamics damping="1.0" friction="0.2"/>
  </joint>
  
  <link name="link1">
    <xacro:inertial_simple mass="2.0" ixx="0.008" iyy="0.008" izz="0.005"/>
    <visual>
      <origin xyz="0 0 0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.065"/>
      </geometry>
      <material name="pipe_base">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <visual>
      <origin xyz="0 0.06 0.0065" rpy="${PI_2} 0 0"/>
      <geometry><cylinder radius="0.03" length="0.12"/></geometry>
      <material name="pipe_grey"><color rgba="0.7 0.7 0.75 1.0"/></material>
    </visual>
    <visual>
      <origin xyz="0 0.12 0.0065" rpy="0 0 0"/>
      <geometry><sphere radius="0.03"/></geometry>
      <material name="pipe_fitting"><color rgba="0.3 0.3 0.35 1.0"/></material>
    </visual>
    <visual>
      <origin xyz="0 0.12 0.0815" rpy="0 0 0"/>
      <geometry><cylinder radius="0.03" length="0.15"/></geometry>
      <material name="pipe_grey"/>
    </visual>
    <visual>
      <origin xyz="0 0.12 0.1565" rpy="0 0 0"/>
      <geometry><sphere radius="0.03"/></geometry>
      <material name="pipe_fitting"/>
    </visual>
    <visual>
      <origin xyz="0 0.06 0.1565" rpy="${PI_2} 0 0"/>
      <geometry><cylinder radius="0.03" length="0.12"/></geometry>
      <material name="pipe_grey"/>
    </visual>
    <visual>
      <origin xyz="0 0 0.1565" rpy="${PI_2} 0 0"/>
      <geometry><cylinder radius="0.03" length="0.05"/></geometry>
      <material name="pipe_head"><color rgba="0.2 0.2 0.2 1.0"/></material>
    </visual>
  </link>

  <link name="lidar_link">
    <xacro:inertial_simple mass="0.1" ixx="0.0001" iyy="0.0001" izz="0.0001"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.00825"/>
      </geometry>
      <material name="lidar_embedded">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="lidar_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.0807" rpy="0 0 0"/>
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0.1565" rpy="${PI_2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.8" upper="${PI_2}" effort="20.0" velocity="1.5"/>
    <dynamics damping="15.0" friction="5.0"/>
  </joint>
  
  <link name="link2">
    <xacro:inertial_simple mass="0.7" ixx="0.001" iyy="0.006" izz="0.006"/>
    <visual>
      <origin xyz="0.15 0 0" rpy="0 ${PI_2} 0"/>
      <geometry><cylinder radius="0.035" length="0.30"/></geometry>
      <material name="link2_mat"><color rgba="0.8 0.8 0.8 1"/></material>
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="0.08"/></geometry>
      <material name="link2_flange_root"><color rgba="0.90 0.90 0.90 1.0"/></material>
    </visual>
    <visual>
      <origin xyz="0.30 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="0.08"/></geometry>
      <material name="link2_flange_tip"><color rgba="0.90 0.90 0.90 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0.15 0 0" rpy="0 ${PI_2} 0"/>
      <geometry><cylinder radius="0.035" length="0.25"/></geometry>
    </collision>
  </link>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="palm_link"/>
    <origin xyz="0.30 0 0" rpy="${PI_2} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${PI_2}" upper="0.0" effort="10.0" velocity="1.5"/>
    <dynamics damping="1.0" friction="0.2"/>
  </joint>

   <link name="palm_link">
    <xacro:inertial_simple mass="0.8" ixx="0.001" iyy="0.001" izz="0.001"/>
    <visual>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry><box size="0.04 0.12 0.06"/></geometry>
      <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0"/></material>
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder radius="0.04" length="0.01"/></geometry>
      <material name="metal_grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry><box size="0.04 0.12 0.06"/></geometry>
    </collision>
  </link>

  <xacro:macro name="industrial_wrench_finger" params="suffix reflect color">
    <link name="finger${suffix}_link">
      <xacro:inertial_simple mass="0.3" ixx="0.0002" iyy="0.0002" izz="0.0002"/>
      <visual>
        <origin xyz="0.035 0 0" rpy="0 0 0"/>
        <geometry><box size="0.07 0.01 0.03"/></geometry>
        <material name="${color}"><color rgba="1.0 0.5 0.0 1.0"/></material>
      </visual>
      <visual>
        <origin xyz="0.015 ${reflect * 0.006} 0" rpy="0 0 0"/>
        <geometry><box size="0.04 0.012 0.05"/></geometry>
        <material name="dark_grey"/>
      </visual>
      <visual>
        <origin xyz="0.05 ${reflect * 0.005} 0" rpy="0 0 ${reflect * -0.15}"/>
        <geometry><box size="0.05 0.008 0.03"/></geometry>
        <material name="dark_grey"/>
      </visual>
      <visual>
        <origin xyz="0.055 ${reflect * -0.006} 0" rpy="0 0 0"/>
        <geometry><box size="0.025 0.005 0.025"/></geometry>
        <material name="rubber_black"><color rgba="0.05 0.05 0.05 1.0"/></material>
      </visual>

      <collision>
        <origin xyz="0.035 ${reflect * -0.005} 0" rpy="0 0 0"/>
        <geometry><box size="0.07 0.01 0.04"/></geometry>
      </collision>
    </link>

    <joint name="finger${suffix}_joint1" type="prismatic">
      <parent link="palm_link"/>
      <child link="finger${suffix}_link"/>
      <origin xyz="0.04 ${reflect * 0.008} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <xacro:if value="${reflect == 1}">
        <limit lower="-0.005" upper="0.04" effort="300.0" velocity="0.1"/>
      </xacro:if>
      <xacro:if value="${reflect == -1}">
        <limit lower="-0.04" upper="0.005" effort="300.0" velocity="0.1"/>
      </xacro:if>
      <dynamics damping="10.0" friction="5.0"/>
    </joint>

    <gazebo reference="finger${suffix}_link">
      <mu1>100.0</mu1>
      <mu2>100.0</mu2>
      <kp>10000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.05</minDepth>
      <maxVel>0.1</maxVel>
      <material>Gazebo/Orange</material>
    </gazebo>
  </xacro:macro>
  <xacro:industrial_wrench_finger suffix="1" reflect="1"  color="ind_orange"/>
  <xacro:industrial_wrench_finger suffix="2" reflect="-1" color="ind_orange"/>

  <ros2_control name="me332_mm_system" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>



    <joint name="joint1">
      <command_interface name="position"/>
      <state_interface name="position"/><state_interface name="velocity"/>
    </joint>

    <joint name="joint2">
      <command_interface name="position">
        <param name="initial_value">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.57</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>

    <joint name="joint3">
      <command_interface name="position"/>
      <state_interface name="position"/><state_interface name="velocity"/>
    </joint>

    <joint name="finger1_joint1">
      <command_interface name="position"/>
      <state_interface name="position"/><state_interface name="velocity"/>
    </joint>
    <joint name="finger2_joint1">
      <command_interface name="position"/>
      <state_interface name="position"/><state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <xacro:if value="${controllers_yaml_path != ''}">
          <parameters>${controllers_yaml_path}</parameters>
      </xacro:if>
    </plugin>
  </gazebo>
  
  <gazebo reference="lidar_link">
    <sensor name="embedded_lidar" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <always_on>true</always_on>
      <visualize>false</visualize>
      <update_rate>20</update_rate>
      <ray>
        <scan>
          <horizontal><samples>360</samples><resolution>1</resolution><min_angle>-3.14159</min_angle><max_angle>3.14159</max_angle></horizontal>
        </scan>
        <range><min>0.20</min><max>10.0</max><resolution>0.01</resolution></range>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros><remapping>~/out:=scan</remapping></ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
    <material>Gazebo/Grey</material>
  </gazebo>
 
  <gazebo>
    <plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
      <arm>
        <arm_name>me332_mobile_manipulator</arm_name>
        <palm_link>palm_link</palm_link>
        <gripper_link>finger1_link</gripper_link>
        <gripper_link>finger2_link</gripper_link>
      </arm>
      <forces_angle_tolerance>100</forces_angle_tolerance>
      <update_rate>150</update_rate>
      <grip_count_threshold>2</grip_count_threshold>
      <max_grip_count>8</max_grip_count>
      <release_tolerance>0.005</release_tolerance>
      <disable_collisions_on_attach>true</disable_collisions_on_attach>
      <contact_topic>__default_topic__</contact_topic>
    </plugin>
  </gazebo>

    <gazebo reference="base_link">
    <sensor name="imu_sensor" type="imu">
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
          <remapping>~/out:=imu</remapping>
        </ros>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
    </sensor>
  </gazebo>
  
  <gazebo reference="base_link">

    <material>Gazebo/DarkGrey</material>
  </gazebo>
  
  <gazebo reference="arm_base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="link1">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="link2">
    <material>Gazebo/White</material>
  </gazebo>

  <gazebo reference="palm_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <remapping>/cmd_vel:=/base_controller/cmd_vel_unstamped</remapping>
        <remapping>/odom:=/base_controller/odom</remapping>
      </ros>

      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>

      <wheel_separation>${wheel_sep}</wheel_separation>
      <wheel_diameter>${2*wheel_r}</wheel_diameter>

      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf> 
      <publish_wheel_tf>false</publish_wheel_tf>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>
  <gazebo>
    <plugin name="wheel_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>
      <joint_name>front_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_joint</joint_name>
      <joint_name>rear_left_wheel_joint</joint_name>
      <joint_name>rear_right_wheel_joint</joint_name>
    </plugin>
  </gazebo>
</robot>
